### ISSUE TITLE
IDE fails to start

### ISSUE THREAD

**Issue by coldhamix** [NEzyaka/Turnip-Editor#1]
Turnip-Editor won't start with an error message: 

> This application failed to start because it could not find or load the Qt platform plugin "windows". Reinstalling the application may fix this problem.

**Comment by NEzyaka** [comment]
@coldhamix check dll's version, because my version is 5.5.1.

**Comment by coldhamix** [comment]
Managed to fix this issue on my local machine. The folder _plugins/platforms_ should not be in _plugins_ folder, but in the root IDE folder.
